proj/app/urls.py
from django.conf.urls import url, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r"^$", views.Index.as_view(), name="index"),
    url(r"^", include("app.vendor.urls", namespace="vendor")),
    url(r"^staff/", include("app.staff.urls", namespace="staff")),
    url(r"^api/", include("app.api.urls", namespace="api")),
    url(r"^auth/", include("users.auth.urls")),
]
if settings.DEBUG:
  urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

proj/events/urls.py
from django.urls import path

from .viewsets import (
    EventsListViewSet,
    EventsViewSet,
)

urlpatterns = [
    path("", EventsListViewSet.as_view({
        "get": "list",
    }), name="notices"),
    path("/<int:pk>/", EventsViewSet.as_view({
        "patch": "partial_update"
    }), name="notice_detail")
]

proj/app/templates/app/interfaces/notices/list.html
{% extends 'app/base.html' %}
{% load templatetags %}
{% block content %}
    {% block events %}
        <div class="events mt-2">
            <div class="events__title title">
                <div class="row d-flex justify-content-between">
                    <div class="col-6">
                        <h1>Уведомления</h1>
                    </div>
                    <div class="col-6 d-flex justify-content-end align-items-center">
                        {% block notices__clear %}
                        <a href="#" data-action="{% url 'vendor:notices' %}" class="js-notices-clear btn btn-success btn-sm">Отметить все прочитанными</a>
                        {% endblock %}
                    </div>
                </div>
            </div>
            <div class="events-items">
                {% for notice in notices %}
                    {% if notice.is_active %}
                        <div class="event-item alert alert-secondary alert-dismissible fade show" role="alert">
                            <div class="event-item__created">
                                {{notice.event.pub_date |date:'H:i d-m-Y'}}
                            </div>
                            <div class="event-item__title">
                                <strong>{{ notice.title |safe}}</strong>
                                {% if notice.link %}
                                    <div>
                                        {{ notice.link | safe}}
                                    </div>
                                {% endif %}
                            </div>
                            {% if notice.description %}
                                <hr>
                                <div class="event-item__description">
                                    {{ notice.description }}
                                </div>
                            {% endif %}
                            {% block button-notice__disable %}
                                <button type="button" class="close js-notice-disable" data-dismiss="alert"
                                        aria-label="Close" data-action="{% url 'vendor:notice_detail' pk=notice.pk %}">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            {% endblock %}
                        </div>
                    {% endif %}
                {% endfor %}
            </div>
        </div>
    {% endblock %}
{% endblock %}