proj/app/staff/urls.py
from django.urls import path
from . import views
from app.staff.viewsets import *

app_name = "staff"

urlpatterns = [
    path("", views.StaffTenderList.as_view(), name="index"),
    # path("detail/<int:pk>/", views.StaffTenderDetail.as_view(), name="tender_detail"),
    path("detail/<int:pk>/close", views.CloseTender.as_view(), name="tender_close"),
    path(
        "detail/<int:pk>/",
        StaffTenderDetailViewSet.as_view(
            {
                "get": "retrieve",
                "patch": "partial_update",
            }
        ),
        name="tender_detail",
    ),
    path("archive/", views.StaffArchiveList.as_view(), name="tender_archive"),
    path("notices/", StaffNoticeListViewSet.as_view({
        "get": "list",
        "delete": "destroy",
    }), name="notices"),
    path("notices/<int:pk>/", StaffNoticeViewSet.as_view({
        "patch": "partial_update",
    }), name="notice_detail"),
    path("rooms/", StaffRoomListViewSet.as_view({
        "get": "list",
        "post": "create",
    }), name="rooms"),
    path(
        "rooms/<int:pk>/",
        StaffRoomDetailViewSet.as_view(
            {
                "get": "retrieve",
                "put": "create",
            }
        ),
        name="room_detail",
    ),
    path(
        "profile/",
        ProfileViewSet.as_view({"get": "retrieve", "patch": "partial_update"}),
        name="profile",
    ),
    path(
        "vendors/",
        VendorViewSet.as_view({"get": "list", "post": "create", "put": "create"}),
        name="vendor_list",
    ),
    path(
        "vendors/<int:pk>/",
        VendorDetailViewSet.as_view(
            {
                "get": "retrieve",
                "put": "update",
                "patch": "partial_update",
                "delete": "destroy",
            }
        ),
        name="vendor_detail",
    ),
    path(
        "vendors/<int:vendor_pk>/documents/",
        VendorDocumentsViewSet.as_view(
            {"get": "list", "put": "create", "post": "create"}
        ),
        name="vendor_documents",
    ),
    path(
        "vendors/<int:vendor_pk>/documents/<int:pk>/",
        VendorDocumentsDetailViewSet.as_view(
            {
                "get": "retrieve",
                "put": "update",
                "patch": "partial_update",
                "delete": "destroy",
            }
        ),
        name="vendor_document",
    ),
    path(
        "vendors/<int:vendor_pk>/cars/",
        VendorCarsViewSet.as_view({"get": "list", "put": "create", "post": "create"}),
        name="vendor_cars",
    ),
    path(
        "vendors/<int:vendor_pk>/cars/<int:pk>/",
        VendorCarsDetailViewSet.as_view(
            {
                "get": "retrieve",
                "put": "update",
                "patch": "partial_update",
                "delete": "destroy",
            }
        ),
        name="vendor_car",
    ),
    path(
        "vendors/<int:vendor_pk>/drivers/",
        VendorDriversViewSet.as_view(
            {"get": "list", "put": "create", "post": "create"}
        ),
        name="vendor_drivers",
    ),
    path(
        "vendors/<int:vendor_pk>/driver/<int:pk>/",
        VendorDriversDetailViewSet.as_view(
            {
                "get": "retrieve",
                "put": "update",
                "patch": "partial_update",
                "delete": "destroy",
            }
        ),
        name="vendor_driver",
    ),
    path(
        "manager/",
        ManagerViewSet.as_view({"get": "list", "put": "create", "post": "create"}),
        name="manager_list",
    ),
    path(
        "manager/<int:pk>/",
        ManagerDetailViewSet.as_view(
            {
                "get": "retrieve",
                "put": "update",
                "patch": "partial_update",
                "delete": "destroy",
            }
        ),
        name="manager_detail",
    ),
]

proj/app/urls.py
from django.conf.urls import url, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r"^$", views.Index.as_view(), name="index"),
    url(r"^", include("app.vendor.urls", namespace="vendor")),
    url(r"^staff/", include("app.staff.urls", namespace="staff")),
    url(r"^api/", include("app.api.urls", namespace="api")),
    url(r"^auth/", include("users.auth.urls")),
]
if settings.DEBUG:
  urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

proj/app/templates/app/interfaces/messages/room_detail.html
{% extends 'app/base.html' %}
{% block content %}
    {% block messages %}
        <div class="container">
            <h3 class=" text-center mt-2 mb-3">{{ room_profile.name }}</h3>
            <div class="messaging">
                <div class="inbox_msg">
                    <div class="mesgs">
                        <div class="msg_history js-message-body">
                            {% for message in messages %}
                                {% if message.sender == request.user %}
                                    <div class="incoming_msg">
                                        <div class="received_msg">
                                            <div class="received_withd_msg">
                                                <p>{{ message.message }}</p>
                                                <span class="time_date">{{ message.updated }}</span></div>
                                        </div>
                                    </div>
                                {% else %}
                                    <div class="outgoing_msg">
                                        <div class="sent_msg">
                                            <p>{{ message.message }}</p>
                                            <div class="msg-detail d-flex justify-content-between">
                                                <span class="time_date">{{ message.updated }}</span>
                                                <span class="time_date mr-5">{{ room_profile.name }}</span>
                                            </div>
                                        </div>
                                    </div>
                                {% endif %}
                            {% endfor %}
                        </div>
                        <div class="type_msg">
                            <div class="input_msg_write">
                                {% block room-form %}
                                    <form action="{% url 'vendor:room_detail' pk=room_profile.room.pk %}"
                                          class="js-form-message">
                                        <input type="text" name="message" class="js-form-field write_msg js-message"
                                               placeholder="Ваше сообщение"/>
                                        <input type="hidden" name="room" class="js-form-field"
                                               value="{{ room_profile.room.pk }}"/>
                                        <button class="msg_send_btn js-message-send" type="submit"
                                                data-room="{{ room_profile.room.pk }}">
                                            <i class="fas fa-paper-plane"></i>
                                        </button>
                                    </form>
                                {% endblock %}

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    {% endblock %}
{% endblock %}

proj/app/templates/app/interfaces/messages/room_list.html
{% extends 'app/base.html' %}
{% load rest_framework %}

{% block content %}
    {% block rooms %}
        <div class="events mt-2">
            <div class="events__title title"><h1>Ваши последние контакты</h1></div>
            {% block rooms__link-message %}
                <div class="row">
                    <div class="col-12 mt-3 mb-3">
                        <a href="{% url 'vendor:rooms' %}" class="js-room-create btn btn-light btn-block rounded-0">Написать сообщение</a>
                    </div>
                </div>
            {% endblock %}

            <div class="events-items">
                {% for room in rooms %}
                    <div class="event-item alert alert-secondary alert-dismissible fade show"
                         role="alert">
                        <div class="event-item__title d-flex justify-content-between">
                            {% block rooms__link-detail %}
                                <a href="{% url 'vendor:room_detail' pk=room.room.pk %}">{{ room.name }}</a>
                            {% endblock %}
                            {% if room.unread > 0 %}
                                <strong>новых сообщений: {{ room.unread }}</strong>
                            {% endif %}
                        </div>
                        {% block button-room__disable %}
                            <button type="button" class="close js-room-disable" data-dismiss="alert"
                                    aria-label="Close" data-action="">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        {% endblock %}
                    </div>
                {% endfor %}
            </div>
        </div>
    {% endblock %}
{% endblock %}