proj/app/urls.py
from django.conf.urls import url, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r"^$", views.Index.as_view(), name="index"),
    url(r"^", include("app.vendor.urls", namespace="vendor")),
    url(r"^staff/", include("app.staff.urls", namespace="staff")),
    url(r"^api/", include("app.api.urls", namespace="api")),
    url(r"^auth/", include("users.auth.urls")),
]
if settings.DEBUG:
  urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

proj/app/models.py
from django.db import models
from django.utils import timezone
from django.utils.timezone import datetime
from django.contrib.auth.models import User
from datetime import timedelta, time
from django.dispatch import receiver
from django.db.models.signals import post_save, pre_save, post_delete
import logging
# import ipdb

DEFAULT_BET_STEP = 500

TENDER_STATUS = (
    ("new", "новый"),
    ("played", "играет"),
    ("closed", "закрыт"),
    ("archive", "архив"),
)

TASK_UNLOADING = (
    ("back", "задняя"),
    ("side", "боковая"),
    ("top", "верхняя"),
    ("other", "любая"),
)


class Tender(models.Model):
    publication = models.BooleanField("Публиковать?", default=True)
    code = models.IntegerField("CODE", null=True, blank=True)
    name = models.CharField("Название тендера", max_length=255, blank=False, null=False)
    status = models.CharField(
        "Статус", max_length=20, choices=TENDER_STATUS, default="new"
    )
    pub_date = models.DateTimeField("Дата создания", default=timezone.now)
    date_start = models.DateTimeField(
        "Начало торгов", null=False, blank=False, default=timezone.now
    )
    date_end = models.DateTimeField(
        "Окончание торгов", blank=False, null=False, default=timezone.now
    )
    prolong = models.IntegerField(
        "Продление торгов в секундах", default=0, null=True, blank=True
    )
    bet_step = models.IntegerField("Шаг ставки", default=DEFAULT_BET_STEP)
    bet_win = models.IntegerField("Лучшая ставка", null=True, blank=True)
    bet_init = models.IntegerField("Начальная ставка", blank=True, null=True)
    confirmed = models.BooleanField("Подтвержден", default=False)
    comment = models.TextField("Комментарий", null=True, blank=True)
    user_winner = models.ForeignKey(
        User, on_delete=models.SET_NULL, null=True, blank=True
    )
    vendor_car = models.ForeignKey(
        "users.Car",
        related_name="tenders",
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
    )
    vendor_driver = models.ForeignKey(
        "users.Driver",
        related_name="tenders",
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
    )

    def get_bet_min(self):
        if self.bet_win is not None:
            # ipdb.set_trace()
            bet_min = self.bets.filter(publication=True, bet=self.bet_win).latest("bet")
            # bet_min = self.bets.filter(publication=True, bet=self.bet_win)
            if bet_min is not None:
                return bet_min
        return None

    def bet_enabled_by_status(self):
        if self.status in ("played", "new"):
            return True
        return False

    def achieved_data(self):
        if self.vendor_car is not None and self.vendor_driver is not None:
            return True
        return False

    def enabled_for_bet(self):
        if self.date_end > timezone.now():
            return True
        return False

    def enabled_for_show(self):
        return self.date_start < timezone.now() and self.date_end > timezone.now()

    def get_prolong(self):
        prolong = {
            "hour": self.prolong // 3600,
            "minute": self.prolong // 60 - (self.prolong // 3600) * 60,
        }
        return prolong

    def __str__(self):
        return "#{} {}".format(self.code, self.name)

    class Meta:
        verbose_name = "Тендер"
        verbose_name_plural = "Тендеры"


class Task(models.Model):
    publication = models.BooleanField("Публиковать?", default=True)
    name = models.CharField(
        "Наименование груза", max_length=255, null=False, blank=False
    )
    point_from = models.CharField(
        "Пункт отправления", max_length=50, null=True, blank=True
    )
    point_to = models.CharField(
        "Пункт назначения", max_length=50, null=True, blank=True
    )
    date_start = models.DateTimeField("Дата погрузки", null=True, default=timezone.now)
    date_end = models.DateTimeField("Дата выгрузки", null=True)
    weight = models.CharField("Вес", max_length=255, null=True, blank=True)
    vehicle = models.CharField(
        "Тип ТС", choices=TASK_UNLOADING, null=True, blank=True, max_length=20
    )
    tender = models.ForeignKey("Tender", related_name="tasks", on_delete=models.CASCADE)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Задача"
        verbose_name_plural = "Задачи"


class Bet(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    tender = models.ForeignKey("Tender", on_delete=models.CASCADE, related_name="bets")
    bet = models.PositiveIntegerField("Ставка", null=False, blank=False)
    pub_date = models.DateTimeField("Дата/время ставки", default=timezone.now)
    publication = models.BooleanField("Публиковать?", default=True)

    class Meta:
        verbose_name = "Ставка"
        verbose_name_plural = "Ставки"


class Category(models.Model):
    name = models.CharField("Название", max_length=255)
    parent = models.ForeignKey(
        "self",
        null=True,
        blank=True,
        related_name="children",
        verbose_name="Родительская категория",
        on_delete=models.CASCADE,
    )
    slug = models.SlugField("URL", unique=True, default="")
    pub_date = models.DateTimeField("Дата создания", auto_now_add=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Категория"
        verbose_name_plural = "Категории"


class Page(models.Model):
    title = models.CharField("Заголовок", max_length=255, null=False)
    text = models.TextField("Текст", null=True, blank=True)
    is_active = models.BooleanField("Флаг активности", default=True)
    pub_date = models.DateTimeField("Дата создания", auto_now_add=True)
    slug = models.SlugField("URL", max_length=50, unique=True, default="")
    category = models.ForeignKey(
        "Category",
        on_delete=models.CASCADE,
        null=True,
        blank=True,
        related_name="pages",
    )

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "Страница"
        verbose_name_plural = "Страницы"


class SiteSettings(models.Model):
    tender_created_email_template = models.TextField(
        "Шаблон для письма на созданный тендер", null=True, blank=True
    )

    class Meta:
        verbose_name = "Настройки сайта"
        verbose_name_plural = "Настройки сайта"


# продление тендера, запись лога ставки
@receiver(pre_save, sender=Bet)
def bet_save(sender, instance, **kwargs):
    logger = logging.getLogger("gerkules.bets")
    less20 = False
    change_date_end = False
    tender = instance.tender
    if not instance.pk:
        diff = tender.date_end - timezone.now()
        diff_minutes = diff.seconds // 60
        old_date_end = tender.date_end
        if diff.days == 0 and 0 <= diff_minutes <= 20:
            less20 = True
            if (
                not tender.bets.filter(publication=True).count()
                or not tender.bets.filter(user=instance.user, publication=True).count()
            ):
                change_date_end = True
                prolong = 60 * 20
                tender.date_end = tender.date_end + timedelta(0, prolong)
                try:
                    tender.prolong = tender.prolong + prolong
                except TypeError:
                    tender.prolong = prolong

        log = """
        less20: {less}
        diff (minutes): {diff},
        timezone.now: {timezone}
        old_date_end: {old_date_end}
        tender_date_end: {tender_date_end}
        bet: {bet},
        tender_code: {tender_code},
        username: {username},
        change_date_end_by_user: {change_date_end}
        """.format(
            less=less20,
            diff=diff_minutes,
            timezone=timezone.now().strftime("%Y-%m-%d %H:%M:%S"),
            old_date_end=old_date_end.strftime("%Y-%m-%d %H:%M:%S"),
            tender_date_end=tender.date_end.strftime("%Y-%m-%d %H:%M:%S"),
            bet=instance.bet,
            tender_code=tender.code,
            username=instance.user.username,
            change_date_end=change_date_end
        )
        logger.info(log)


# DEV
# удаление ставок у играющего тендера
# установить статус тендера на новый
@receiver(post_delete, sender=Bet)
def tender_set_bet_default(sender, instance, **kwargs):
    tender = instance.tender
    if tender.status == "played":
        bets = Bet.objects.filter(tender=tender, publication=True)
        if not bets:
            tender.bet_win = None
            tender.status = "new"
            tender.save()

proj/app/templates/app/interfaces/tender/archive.html
{% extends 'app/interfaces/tender/tender.html' %}
{% block tender__status %}
    <div class="col-8">
        {% if tender.status == 'archive' %}
            <div class="row d-flex justify-content-end">
                {% if tender.user_winner == request.user %}
                    <div class="col-4">
                        {% if tender.achieved_data %}
                            <div class="alert alert-success m-0 w-100 p-2 rounded-0">
                                <div class="d-flex justify-content-center">
                                    <span class="mr-2"><i class="fas fa-check-square"></i></span>
                                    <span class="h6 m-0">Документы<br> получены</span>
                                </div>
                            </div>
                        {% else %}
                            <div class="alert alert-warning m-0 w-100 p-2 rounded-0">
                                <div class="d-flex justify-content-center">
                                    <span class="mr-2"></span>
                                    <span class="h6 m-0">Документы<br>НЕ получены</span>
                                </div>
                            </div>
                        {% endif %}
                    </div>
                    <div class="col-4">
                        {% if tender.confirmed %}
                            <div class="alert alert-success m-0 w-100 p-2 rounded-0">
                                <div class="d-flex justify-content-center">
                                    <span class="mr-2"><i class="fas fa-check-square"></i></span>
                                    <span class="h6 m-0">Сыграл. <br> Подтвержден</span>
                                </div>
                            </div>
                        {% else %}
                            <div class="alert alert-warning m-0 w-100 p-2 rounded-0">
                                <div class="d-flex justify-content-center">
                                    <span class="mr-2"></span>
                                    <span class="h6 m-0">Не подтвержден</span>
                                </div>
                            </div>
                        {% endif %}
                    </div>
                    <div class="col-4">
                        <div class="row d-flex justify-content-end h-100">
                            <div class="col">
                                <div class="alert alert-secondary m-0 w-100 p-2 rounded-0 h-100">
                                    <div class="d-flex justify-content-center align-items-center h-100">
                                        <span class="mr-2"><i class="fas fa-hourglass-end"></i></span>
                                        <span class="h6 m-0">{{ tender.get_status_display }}</span>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                {% else %}
                    {% if tender.user_winner and tender.confirmed and tender.achieved_data %}
                        <div class="col-4">
                            <div class="alert alert-warning m-0 w-100 p-2 rounded-0">
                                <div class="d-flex justify-content-center">
                                    <span class="mr-2"><i class="fas fa-trophy"></i></span>
                                    <span class="h6 m-0">Была победа</span>
                                </div>
                            </div>
                        </div>
                    {% endif %}
                    <div class="col-4">
                        <div class="alert alert-secondary m-0 w-100 p-2 rounded-0">
                            <div class="d-flex justify-content-center">
                                <span class="mr-2"><i class="fas fa-hourglass-end"></i></span>
                                <span class="h6 m-0">{{ tender.get_status_display }}</span>
                            </div>
                        </div>
                    </div>
                {% endif %}
            </div>
        {% endif %}
    </div>
{% endblock %}
{% block tender__best-bet-val %}
    {% if tender.status == "archive" %}
        {% if tender.user_bet %}
            {% if tender.user_bet == tender.bet_min %}
                <span class="font-weight-bold text-success">{{ tender.bet_min }}</span>
            {% else %}
                <span class="font-weight-bold">{{ tender.bet_min }}</span>
                <br>
                (
                <span class="font-weight-bold text-danger">{{ tender.user_bet }}</span>
                )
            {% endif %}
        {% elif tender.bet_min %}
            <span class="font-weight-bold">{{ tender.bet_min }}</span>
        {% else %}
            <span class="font-weight-bold"> - </span>
        {% endif %}
    {% elif tender.status == "closed" %}
        {{ vendor.company_name }}<br>
        (
        <span class="font-weight-bold text-success">{{ tender.user_bet }}</span>
        )
    {% endif %}
{% endblock %}

proj/app/templates/app/interfaces/tender/bets.html
{% if bets %}
    {% for bet in bets %}
    <p>{{bet.bet}}</p>
    {% endfor %}
{% endif %}

proj/app/templates/app/interfaces/tender/detail.html
{% extends  'app/base.html' %}
{% load templatetags %}
{% block content %}
    {% block breadcrumbs %}
        <div class="row">
            <div class="col breadcrumb"></div>
        </div>
    {% endblock %}
    <div class="row">
        <div class="col-12">
            {% block detail %}
                {% block detail__errors %}
                    {% if messages %}
                        <div class="text-alert">
                            {% for message in messages %}
                                {% get_bootstrap_alert_msg message.tags as alert_tag %}
                                <div class="alert alert-{{ alert_tag }}" role="alert">
                                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×
                                    </button>
                                    {{ message }}
                                </div>
                            {% endfor %}
                        </div>
                    {% endif %}
                {% endblock %}
                {% block detail__header %}
                    <div class=""><span class="font-weight-bold h3 mr-2">№{{ tender.code }}</span> <span
                            class="h4">{{ tender.name }}</span></div>
                    <div class="row mt-4">
                        <div class="col">
                            <h5>Общие данные</h5>
                        </div>
                    </div>
                    <div class="row mt-3 mb-3">
                        <div class="col-4">
                            <div>Тип тендера: <b>{{ tender.type }}</b></div>
                            <div>Начало торгов: <b>{{ tender.date_start }}</b></div>
                            <div class="tender__dateend">
                                <div class="tender__dateend-date">
                                    Окончание торгов: <b>{{ tender.date_end }}</b>
                                </div>
                                {% if tender.prolong %}
                                    <div class="tender__dateend-prolong">
                                            ( +{{tender.get_prolong.hour}}ч.:{{tender.get_prolong.minute}}м. )
                                    </div>
                                {% endif %}
                            </div>
                        </div>
                        <div class="col-8">
                            <div class="row">
                                {% block detail__data %}
                                    <div class="col-4">
                                        {% block detail__tender-bet-status %}
                                            {% if tender.bet_start %}
                                                <div>Начальная ставка: <b>{{ tender.bet_start }}</b></div>
                                            {% endif %}
                                            {% block detail__bet-win %}
                                                {% if tender.bet_win %}
                                                    <div>Лучшая ставка: <b class="">{{ tender.bet_win }}</b></div>
                                                {% endif %}
                                                {% if bet_min_user %}
                                                    <div class="">Ваша ставка:
                                                        <b class="{% if bet_min_user == tender.bet_win %}text-success{% else %}text-danger{% endif %}">{{ bet_min_user }}
                                                        </b>
                                                    </div>
                                                {% endif %}
                                            {% endblock %}
                                            <div><a href="#">история ставок</a></div>
                                        {% endblock %}
                                    </div>
                                    <div class="col-3">
                                        {% block detail__tender-status %}
                                            {% if tender.status == "new" %}
                                                {% define "secondary" as alert_classname %}
                                                {% define "fa-hourglass-start" as icon_classname %}
                                            {% elif tender.status == "played" %}
                                                {% define "primary" as alert_classname %}
                                                {% define "fa-hourglass-half" as icon_classname %}
                                            {% elif tender.status == "closed" %}
                                                {% define "secondary" as alert_classname %}
                                                {% define "fa-hourglass-end" as icon_classname %}
                                            {% endif %}
                                            <div class="alert alert-{{ alert_classname }} rounded-0 m-0 p-2">
                                                <div class="d-flex justify-content-center">
                                                    <span class="mr-2"><i class="fas {{ icon_classname }}"></i></span>
                                                    <span class="h6 m-0">{{ tender.get_status_display }}</span>
                                                </div>
                                            </div>
                                        {% endblock %}
                                    </div>
                                {% endblock %}
                            </div>
                        </div>
                    </div>
                {% endblock %}
                {% block detail__task %}
                    <div class="row">
                        <div class="col">
                            <table class="table">
                                <thead class="thead-light">
                                <tr>
                                    <th scope="col">Пункт отправления</th>
                                    <th scope="col">Пункт назначения</th>
                                    <th scope="col">Наименование груза</th>
                                    <th scope="col">Дата/время погрузки</th>
                                    <th scope="col">Дата/время выгрузки</th>
                                    <th scope="col">Вес/кол-во паллет</th>
                                    <th scope="col">Тип ТС</th>
                                </tr>
                                </thead>
                                <tbody>
                                {% for task in tasks %}
                                    <tr>
                                        <td>{{ task.point_from }}</td>
                                        <td>{{ task.point_to }}</td>
                                        <td>{{ task.name }}</td>
                                        <td>{{ task.date_start }}</td>
                                        <td>{{ task.date_end }}</td>
                                        <td>{{ task.weight }}</td>
                                        <td>{{ task.get_vehicle_display }}</td>
                                    </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                {% endblock %}
                {% block detail__comment %}
                    {% if tender.comment %}
                        <div class="row">
                            <div class="col">
                                <div class="tender__comment text">
                                    <p>{{tender.comment|safe}}</p>
                                </div>
                            </div>
                        </div>
                    {% endif %}
                {% endblock %}
                {% block detail__winner %}
                {% endblock %}
                {% block detail__bets %}
                    {% if bets %}
                        <div class="row mt-5">
                            <div class="col">
                                <div class="row">
                                    <div class="col-6">
                                        <h5>История ставок</h5>
                                    </div>
                                    <div class="col-6 d-flex justify-content-end">
                                        {% block detail__bet-cancel %}

                                        {% endblock %}
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col">
                                        <table class="table table-sm table-stripped">
                                            <thead class="thead-light">
                                            <tr>
                                                {#                                        <th scope="col">#</th>#}
                                                <th scope="col">Поставщик</th>
                                                <th scope="col">Время ставки</th>
                                                <th scope="col">Ставка</th>
                                            </tr>
                                            </thead>
                                            <tbody>
                                            {% for bet in bets %}
                                                {% if bet.publication %}
                                                    <tr class="{% if bet.bet == tender.bet_win %}table-success{% endif %}">
                                                        <td>{{ bet.user.vendoruser.company_name }}</td>
                                                        <td>{{ bet.pub_date }}</td>
                                                        <td>{{ bet.bet }}</td>
                                                    </tr>
                                                {% else %}
                                                    <tr class="table-danger">
                                                        <td>{{ bet.user.vendoruser.company_name }}</td>
                                                        <td>{{ bet.pub_date }}</td>
                                                        <td>{{ bet.bet }}: отказ от ставки</td>
                                                    </tr>
                                                {% endif %}
                                            {% endfor %}
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                            </div>
                        </div>
                    {% endif %}
                {% endblock %}
            {% endblock %}
        </div>
    </div>
{% endblock %}