proj/app/staff/urls.py
from django.urls import path
from . import views
from app.staff.viewsets import *

app_name = "staff"

urlpatterns = [
    path("", views.StaffTenderList.as_view(), name="index"),
    # path("detail/<int:pk>/", views.StaffTenderDetail.as_view(), name="tender_detail"),
    path("detail/<int:pk>/close", views.CloseTender.as_view(), name="tender_close"),
    path(
        "detail/<int:pk>/",
        StaffTenderDetailViewSet.as_view(
            {
                "get": "retrieve",
                "patch": "partial_update",
            }
        ),
        name="tender_detail",
    ),
    path("archive/", views.StaffArchiveList.as_view(), name="tender_archive"),
    path("notices/", StaffNoticeListViewSet.as_view({
        "get": "list",
        "delete": "destroy",
    }), name="notices"),
    path("notices/<int:pk>/", StaffNoticeViewSet.as_view({
        "patch": "partial_update",
    }), name="notice_detail"),
    path("rooms/", StaffRoomListViewSet.as_view({
        "get": "list",
        "post": "create",
    }), name="rooms"),
    path(
        "rooms/<int:pk>/",
        StaffRoomDetailViewSet.as_view(
            {
                "get": "retrieve",
                "put": "create",
            }
        ),
        name="room_detail",
    ),
    path(
        "profile/",
        ProfileViewSet.as_view({"get": "retrieve", "patch": "partial_update"}),
        name="profile",
    ),
    path(
        "vendors/",
        VendorViewSet.as_view({"get": "list", "post": "create", "put": "create"}),
        name="vendor_list",
    ),
    path(
        "vendors/<int:pk>/",
        VendorDetailViewSet.as_view(
            {
                "get": "retrieve",
                "put": "update",
                "patch": "partial_update",
                "delete": "destroy",
            }
        ),
        name="vendor_detail",
    ),
    path(
        "vendors/<int:vendor_pk>/documents/",
        VendorDocumentsViewSet.as_view(
            {"get": "list", "put": "create", "post": "create"}
        ),
        name="vendor_documents",
    ),
    path(
        "vendors/<int:vendor_pk>/documents/<int:pk>/",
        VendorDocumentsDetailViewSet.as_view(
            {
                "get": "retrieve",
                "put": "update",
                "patch": "partial_update",
                "delete": "destroy",
            }
        ),
        name="vendor_document",
    ),
    path(
        "vendors/<int:vendor_pk>/cars/",
        VendorCarsViewSet.as_view({"get": "list", "put": "create", "post": "create"}),
        name="vendor_cars",
    ),
    path(
        "vendors/<int:vendor_pk>/cars/<int:pk>/",
        VendorCarsDetailViewSet.as_view(
            {
                "get": "retrieve",
                "put": "update",
                "patch": "partial_update",
                "delete": "destroy",
            }
        ),
        name="vendor_car",
    ),
    path(
        "vendors/<int:vendor_pk>/drivers/",
        VendorDriversViewSet.as_view(
            {"get": "list", "put": "create", "post": "create"}
        ),
        name="vendor_drivers",
    ),
    path(
        "vendors/<int:vendor_pk>/driver/<int:pk>/",
        VendorDriversDetailViewSet.as_view(
            {
                "get": "retrieve",
                "put": "update",
                "patch": "partial_update",
                "delete": "destroy",
            }
        ),
        name="vendor_driver",
    ),
    path(
        "manager/",
        ManagerViewSet.as_view({"get": "list", "put": "create", "post": "create"}),
        name="manager_list",
    ),
    path(
        "manager/<int:pk>/",
        ManagerDetailViewSet.as_view(
            {
                "get": "retrieve",
                "put": "update",
                "patch": "partial_update",
                "delete": "destroy",
            }
        ),
        name="manager_detail",
    ),
]

proj/app/urls.py
from django.conf.urls import url, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r"^$", views.Index.as_view(), name="index"),
    url(r"^", include("app.vendor.urls", namespace="vendor")),
    url(r"^staff/", include("app.staff.urls", namespace="staff")),
    url(r"^api/", include("app.api.urls", namespace="api")),
    url(r"^auth/", include("users.auth.urls")),
]
if settings.DEBUG:
  urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

proj/app/staff/views.py
from django.views.generic import View
from django.shortcuts import redirect, reverse
from django.http import Http404
from django.contrib import messages
from django.conf import settings

from app.models import Tender, Bet, Task
from app.views import TenderList, ArchiveList
from app.staff.viewsets import StaffMixin
from app.filters import ArchiveListFilter, StaffArchiveListFilter


class StaffTenderList(StaffMixin, TenderList):
    template_name = "app/staff/tender/tender.html"

    def get_queryset(self):
        qs = Tender.objects.exclude(status="archive").order_by("-pub_date")
        return qs

    def get_context_data(self, object_list=None, *args, **kwargs):
        if object_list is not None:
            for tender in object_list:
                if tender.status == "played" or tender.status == "closed":
                    bet_min_object = tender.bets.filter(publication=True).order_by('bet').first()
                    # tender.bet_min = tender.bets.filter(publication=True).aggregate(Min("bet"))["bet__min"]
                    if bet_min_object is not None:
                        tender.bet_min = bet_min_object.bet
                        tender.vendor = bet_min_object.user.vendoruser
        context = super(StaffTenderList, self).get_context_data(object_list=object_list, *args, **kwargs)
        context.update({"menu": self.get_menu()})
        return context


class StaffArchiveList(StaffMixin, ArchiveList):
    template_name = "app/staff/tender/archive.html"
    filterset_class = StaffArchiveListFilter

    def get_filterset_with_kwargs(self, request, queryset=None, **kwargs):
        filterset = StaffArchiveListFilter(request.GET, queryset)
        return filterset

    def get_queryset(self):
        qs = Tender.objects.filter(status="archive").order_by("-pub_date")
        return qs

    def get_context_data(self, object_list=None, *args, **kwargs):
        if object_list is not None:
            for tender in object_list:
                bet_min_object = tender.bets.filter(publication=True).order_by('bet').first()
                if bet_min_object is not None:
                    tender.bet_min = bet_min_object.bet
                    # tender.vendor = bet_min_object.user.vendoruser

        context = super(StaffArchiveList, self).get_context_data(object_list=object_list, *args, **kwargs)
        context.update({"menu": self.get_menu()})
        return context


class CloseTender(StaffMixin, View):
    def post(self, request, *args, **kwargs):
        pk = int(self.kwargs["pk"])
        if pk is not None:
            try:
                tender = Tender.objects.get(pk=pk)
            except Tender.DoesNotExist:
                raise Http404

            tender.status = "closed"
            tender.save()

            messages.add_message(request, messages.SUCCESS, "Тендер успешно закрыт")

        return redirect(reverse("staff:index"))

proj/app/templates/app/staff/admin/manager_list.html
{% extends 'app/staff/user_list.html' %}
{% block button__create %}
    <div class="row">
        <div class="col-12">
            <button class="btn btn-light btn-block rounded-0 js-vendor-create">Добавить менеджера</button>
        </div>
    </div>
{% endblock %}
{% block form-hidden__button %}
    <button type="submit" class="btn btn-success js-form-submit">Добавить</button>
{% endblock %}
{% block form-hidden__action %}
    {% url 'staff:manager_list' %}
{% endblock %}
{% block user__list %}
    {% if manager_list %}
        <table class="table table-stripped users-table">
            <thead>
            <tr>
                <th>Имя пользователя</th>
                <th>ФИО</th>
                <th>E-mail</th>
                <th>Телефон</th>
                <th width="30" class="text-center">Отправить сообщение</th>
                <th width="30" class="text-center">Блокировка</th>
                <th width="30" class="text-center">Редактировать данные</th>
                <th width="30" class="text-center">Сменить пароль</th>
            </tr>
            </thead>
            <tbody>
            {% for manager in manager_list %}
                <tr id="item-{{ manager.pk }}"
                    class=" users-table__row js-vendor-row {{ manager.user.is_active|yesno:",m--lock" }}">
                    <td>
                        {{ manager.user.username }}
                    </td>
                    {#                    <td>{{ manager.user.groups.all.0 }}</td>#}
                    <td>{{ manager.name }}</td>
                    <td>{{ manager.email }}</td>
                    <td>{{ manager.phone }}</td>
                    <td class="text-center">
                        <a href="#" class="js-message-send link-icon users-table__row-btn">
                            <i class="fa fa-comment" style="font-size:18px;"></i>
                        </a>
                    </td>
                    <td class="text-center">
                        <a href="{% url 'staff:manager_detail' pk=manager.pk %}"
                           class="js-user-ban users-table__row-btn {{ manager.user.is_active|yesno:",m--lock" }}"
                           data-pk="{{ vendor.pk }}">
                            <i class="fa fa-lock icon-lock"></i>
                            <i class="fa fas fa-lock-open icon-unlock"></i>
                        </a>
                    </td>
                    <td class="text-center">
                        <a href="{% url 'staff:manager_detail' pk=manager.pk %}"
                           class="js-user-edit users-table__row-btn"><i class="fas fa-edit"></i></a>
                    </td>
                    <td class="text-center">
                        <a href="{% url 'staff:manager_detail' pk=manager.pk %}"
                           class="js-user-changepassword users-table__row-btn"><i class="fas fa-key"></i></a>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    {% endif %}
{% endblock %}